FROM python:3.12-slim

WORKDIR /app

# Copy frontend static files
COPY frontend/src ./frontend/src

EXPOSE 3000

# Serve frontend files
CMD ["python", "-m", "http.server", "3000", "--directory", "frontend/src"]
